name: chronos
description: A sample web application
dependencies:
  angular: any
  browser: any
  google_drive_v2_api: any
  web_components: any
dev_dependencies:
  unittest: any
transformers:
- angular
